name: mdstates-gv
channels:
  - rdkit
  - conda-forge
  - openbabel
dependencies:
  - python>=3.6
  - cython
  - networkx>=2.1
  - pandas
  - numpy
  - rdkit
  - mdtraj
  - openbabel
  - aggdraw
  - pip
  - pip:
      - graphviz
