name: mdstates
channels:
  - rdkit
  - conda-forge
  - openbabel
dependencies:
  - python>=3.6
  - networkx>=2.1
  - pandas
  - numpy
  - rdkit
  - pygraphviz
  - mdtraj
  - openbabel
  - pip
  - pip:
      - aggdraw
